language: c
sudo: false
addons:
  apt:
    packages:
    - libblas-dev
matrix:
  include:
  - os: linux
  - os: osx
script:
- autoreconf -i
- ./configure --prefix="$HOME/.local"
- make
- make check
- make install
